services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "88:80"
    volumes:
      - /mnt/portainer-compose-unpacker/stacks/nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/www:/var/www/html
    networks:
      - web

networks:
  web:
    external: true
